import { describe, it, expect } from "vitest";
import { render, screen, fireEvent } from "@testing-library/react";
import { AuditTimeline } from "../components/audit/AuditTimeline";
import type { AuditEvent } from "../lib/types";

function makeEvent(overrides: Partial<AuditEvent> = {}): AuditEvent {
  return {
    id: Math.random().toString(36).slice(2),
    sessionId: "session-1",
    eventType: "SESSION_CREATED",
    description: "Visit started",
    author: "Dr. Smith",
    metadata: null,
    createdAt: "2026-04-10T14:15:00Z",
    ...overrides,
  };
}

const SAMPLE_EVENTS: AuditEvent[] = [
  makeEvent({
    id: "e1",
    eventType: "SESSION_CREATED",
    description: "Visit started for Jane Doe",
    author: "Dr. Smith",
    createdAt: "2026-04-10T14:00:00Z",
  }),
  makeEvent({
    id: "e2",
    eventType: "AUDIO_CAPTURED",
    description: "Audio recording uploaded",
    author: "Dr. Smith",
    createdAt: "2026-04-10T14:05:00Z",
  }),
  makeEvent({
    id: "e3",
    eventType: "TRANSCRIPT_GENERATED",
    description: "Transcript generated (8 utterances)",
    author: "System",
    createdAt: "2026-04-10T14:06:00Z",
  }),
  makeEvent({
    id: "e4",
    eventType: "SOAP_DRAFT_CREATED",
    description: "SOAP note draft generated by AI",
    author: "AI Engine",
    createdAt: "2026-04-10T14:06:30Z",
  }),
  makeEvent({
    id: "e5",
    eventType: "SOAP_EDITED",
    description: "SOAP note edited by Dr. Smith",
    author: "Dr. Smith",
    metadata: { changedFields: ["subjective", "plan"] } as any,
    createdAt: "2026-04-10T14:10:00Z",
  }),
  makeEvent({
    id: "e6",
    eventType: "REVIEW_REQUESTED",
    description: "Review requested by Dr. Smith",
    author: "Dr. Smith",
    createdAt: "2026-04-10T14:11:00Z",
  }),
  makeEvent({
    id: "e7",
    eventType: "NOTE_APPROVED",
    description: "SOAP note approved by Dr. Smith",
    author: "Dr. Smith",
    createdAt: "2026-04-10T14:15:00Z",
  }),
];

// ---------------------------------------------------------------------------
// Empty state
// ---------------------------------------------------------------------------
describe("AuditTimeline — empty state", () => {
  it("shows empty state when no events", () => {
    render(<AuditTimeline events={[]} />);
    expect(screen.getByTestId("audit-empty")).toBeInTheDocument();
    expect(screen.queryByTestId("audit-timeline")).not.toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Event rendering
// ---------------------------------------------------------------------------
describe("AuditTimeline — event rendering", () => {
  it("renders the correct number of event rows", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    const rows = SAMPLE_EVENTS.map((_, i) => screen.getByTestId(`audit-event-${i}`));
    expect(rows).toHaveLength(7);
  });

  it("shows event description text", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getByText("Visit started for Jane Doe")).toBeInTheDocument();
    expect(screen.getByText("Audio recording uploaded")).toBeInTheDocument();
  });

  it("shows author for each event", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getAllByText("Dr. Smith").length).toBeGreaterThan(0);
    expect(screen.getByText("System")).toBeInTheDocument();
    expect(screen.getByText("AI Engine")).toBeInTheDocument();
  });

  it("renders an icon for each event type", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getByTestId("audit-event-icon-SESSION_CREATED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-AUDIO_CAPTURED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-TRANSCRIPT_GENERATED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-SOAP_DRAFT_CREATED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-SOAP_EDITED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-REVIEW_REQUESTED")).toBeInTheDocument();
    expect(screen.getByTestId("audit-event-icon-NOTE_APPROVED")).toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Badges
// ---------------------------------------------------------------------------
describe("AuditTimeline — badges", () => {
  it("shows green 'Signed' badge for NOTE_APPROVED", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    const badge = screen.getByTestId("audit-event-badge-NOTE_APPROVED");
    expect(badge).toHaveTextContent("Signed");
    expect(badge.className).toContain("emerald");
  });

  it("shows yellow 'Draft' badge for SOAP_DRAFT_CREATED", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    const badge = screen.getByTestId("audit-event-badge-SOAP_DRAFT_CREATED");
    expect(badge).toHaveTextContent("Draft");
    expect(badge.className).toContain("yellow");
  });

  it("shows 'In Review' badge for REVIEW_REQUESTED", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getByTestId("audit-event-badge-REVIEW_REQUESTED")).toHaveTextContent("In Review");
  });

  it("shows 'Audio' badge for AUDIO_CAPTURED", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getByTestId("audit-event-badge-AUDIO_CAPTURED")).toHaveTextContent("Audio");
  });
});

// ---------------------------------------------------------------------------
// Metadata expansion
// ---------------------------------------------------------------------------
describe("AuditTimeline — metadata", () => {
  it("shows 'Show details' toggle for events with metadata", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    // SOAP_EDITED (index 4) has metadata
    expect(screen.getByTestId("audit-event-details-toggle-4")).toBeInTheDocument();
  });

  it("does NOT show 'Show details' for events without metadata", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    // SESSION_CREATED (index 0) has no metadata
    expect(screen.queryByTestId("audit-event-details-toggle-0")).not.toBeInTheDocument();
  });

  it("expands metadata when 'Show details' is clicked", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    fireEvent.click(screen.getByTestId("audit-event-details-toggle-4"));
    expect(screen.getByTestId("audit-event-metadata-4")).toBeInTheDocument();
    expect(screen.getByText(/subjective.*plan/)).toBeInTheDocument();
  });

  it("collapses metadata when clicked again", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    fireEvent.click(screen.getByTestId("audit-event-details-toggle-4"));
    fireEvent.click(screen.getByTestId("audit-event-details-toggle-4"));
    expect(screen.queryByTestId("audit-event-metadata-4")).not.toBeInTheDocument();
  });
});

// ---------------------------------------------------------------------------
// Footer / view history
// ---------------------------------------------------------------------------
describe("AuditTimeline — footer", () => {
  it("shows total event count in footer", () => {
    render(<AuditTimeline events={SAMPLE_EVENTS} />);
    expect(screen.getByTestId("audit-view-history")).toHaveTextContent("7 events total");
  });

  it("shows singular 'event' when only 1 event", () => {
    render(<AuditTimeline events={[makeEvent()]} />);
    expect(screen.getByTestId("audit-view-history")).toHaveTextContent("1 event total");
  });
});
